### ISSUE TITLE
Problem when compile Xcode 9 

### ISSUE THREAD

**Issue by frelei** [vanyaland/IMNetworkReachability#2]
I believe this is just a detail that needs to fix. 

<img width="1379" alt="screen shot 2017-09-22 at 11 36 13" src="https://user-images.githubusercontent.com/2272745/30749601-464204c4-9f8a-11e7-9b15-a8bf8f0940ab.png">

**Comment by frelei** [comment]
I made the changes in the [https://github.com/vanyaland/IMNetworkReachability/pull/3](PR)

**Comment by DeepakPradhan-90** [comment]
installation through cocoapods still gives the same error. Please release new version for pods.

**Comment by ivan-magda** [comment]
@DeepakSingtel works fine for me via CocoaPods installation (Swift 4, Xcode 9.2).
What version of the Swift are you using? May be broken in Swift 3.X.

**Comment by ivan-magda** [comment]
Released new version 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeepakPradhan-90** [comment]
I was on Swift 3.2 as some libraries I use don't support swift 4 yet. And I compiled changing to swift 4 and it gave me same errors. After clean build IMNetworkReachability was fine but other libraries broke.
