### ISSUE TITLE
will this work on iOS (as cocoapods shows)

### ISSUE THREAD

**Issue by syvertsj** [vanyaland/IMNetworkReachability#4]
this passes cocoapods iOS filter, however, the module is not recognized when I try to import it. 
Should this work with iOS?

**Comment by ivan-magda** [comment]
@syvertsj, yes, this definitely should work! Few minutes ago created empty project, configured and all looked fine.
Seems to be a bug in the Xcode - [link](https://stackoverflow.com/questions/32673866/cocoapods-cannot-load-underlying-module-for-x).
Also, double check your `Podfile` configuration.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by syvertsj** [comment]
It seems the optimistic operator in the Podfile may have impacted it. 
It builds and runs, but always returns a "reachable" status for any endpoint.
